language: c
os:
  - linux
compiler:
  - clang
  - gcc
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - gcc-5
env:
  - IO_MULTIPLEXER=select
  - IO_MULTIPLEXER=poll
  - IO_MULTIPLEXER=epoll
before_script:
  - if [ "$CC" = "clang" ]; then cmake . -DCMAKE_C_COMPILER=$(which clang-3.7); fi
  - if [ "$CC" = "gcc" ]; then cmake . -DCMAKE_C_COMPILER=$(which gcc-5); fi
  - cmake . -DCMAKE_BUILD_TYPE=release
script:
  - cmake . -DWORLD_IO_MULTIPLEXER=${IO_MULTIPLEXER} && make && ctest --output-on-failure
