language: c
compiler:
  - clang-3.7
  - gcc-5
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.7
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - gcc-5
before_script:
  - cmake . -DCMAKE_BUILD_TYPE=release
  - if [ "$CC" = "clang-3.7" ]; then cmake . -DCMAKE_AR=$(which llvm-ar-3.7); fi
  - if [ "$CC" = "clang-3.7" ]; then cmake . -DCMAKE_RANLIB=$(which llvm-ranlib-3.7); fi
  - if [ "$CC" = "gcc-5" ]; then cmake . -DCMAKE_AR=$(which gcc-ar-5); fi
  - if [ "$CC" = "gcc-5" ]; then cmake . -DCMAKE_RANLIB=$(which gcc-ranlib-5); fi
script:
  - cmake . -DWORLD_IO_MULTIPLEX_METHOD=select && make && ctest --output-on-failure
  - cmake . -DWORLD_IO_MULTIPLEX_METHOD=poll   && make && ctest --output-on-failure
  - cmake . -DWORLD_IO_MULTIPLEX_METHOD=epoll  && make && ctest --output-on-failure
